# Generated by Django 3.1 on 2020-08-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ID', models.IntegerField(max_length=3)),
                ('ticket_time', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=20)),
                ('user_contact', models.CharField(max_length=10)),
                ('ticket_status', models.CharField(choices=[('Valid', 'VALID'), ('Invalid', 'INVALID')], default='Valid', max_length=7)),
            ],
        ),
    ]
