# Generated by Django 3.1 on 2020-08-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200829_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_ID',
            new_name='ticket_id',
        ),
    ]
