# Generated by Django 3.1 on 2020-08-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20200829_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Valid', 'VALID'), ('Invalid', 'INVALID')], default='Valid', max_length=7),
        ),
    ]
